### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by Michl7** [humbertogontijo/python-roborock#212]
Can someone help me with this error?
i am connected, can list devices and also send commands.

e.g. with test_sound_volume, the command runs (robot beeps) but it shows following error:

```
openhabian@pi4openhabian:~ $ /home/openhabian/rr/bin/roborock command --device_id 50XLKow9WZEjW4ssq6yexf --cmd test_sound_volume
INFO:roborock.cloud_api:Connecting to mqtt
INFO:roborock.cloud_api:Starting mqtt loop
INFO:roborock.cloud_api:Connected to mqtt mqtt-eu.roborock.com:8883
INFO:roborock.cloud_api:Subscribed to topic rr/m/o/onj7tEVB5eG3Uel6HHXVf/9369796a/50XLKow9WZEjW4ssq6yexf
Traceback (most recent call last):
  File "/home/openhabian/rr/bin/roborock", line 8, in <module>
    sys.exit(main())
  File "/home/openhabian/rr/lib/python3.9/site-packages/roborock/cli.py", line 200, in main
    return cli()
  File "/home/openhabian/rr/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/openhabian/rr/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/openhabian/rr/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/openhabian/rr/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/openhabian/rr/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/openhabian/rr/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/openhabian/rr/lib/python3.9/site-packages/roborock/util.py", line 65, in wrapped
    return loop.run_until_complete(func(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/openhabian/rr/lib/python3.9/site-packages/roborock/cli.py", line 139, in command
    await mqtt_client.send_command(cmd, json.loads(params) if params is not None else None)
  File "/home/openhabian/rr/lib/python3.9/site-packages/roborock/cloud_api.py", line 168, in send_command
    self._diagnostic_data[method.name] = {"params": params, "response": response, "error": err}
AttributeError: 'str' object has no attribute 'name'
```

**Comment by Lash-L** [comment]
Seems like you have an outdated version of the package. That could doesn't exist on main.

**Comment by badmin-c** [comment]
I am getting the same error on an automation for my Roborock S4 Max. 

Automation triggers when the following conditions are met:

- All our mobile phones have been logged out of the Wi-Fi for more than 15 minutes
- The automation has not run for at least 18 hours

Then the following actions are triggered:

- Suction power is set to max
- Various rooms are vacuumed
- Wait until Roborock docks
- Suction power is set back to Balanced

It always goes as far as setting suction power to MAX, but after that sometimes (e.g. every second or third time) it fails with 

`str’ object has no attribute ‘name’`

I cannot make out a clear pattern and when I test the automation in HA it always works flawless. 

Automation Code: https://pastebin.com/yx2TtFGU
Full Trace with error: https://pastebin.com/Xxngrb1R

Using HACS Integration, everything up to date.

**Comment by Zananok** [comment]
I have the same issue on "ZRoborock S8 Pro Ultra".
`roborock command --device_id $ID --cmd change_sound_volume --params 10`

> Traceback (most recent call last):
  File "/usr/local/bin/roborock", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/roborock/cli.py", line 200, in main
    return cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/roborock/util.py", line 65, in wrapped
    return loop.run_until_complete(func(*args, **kwargs))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/roborock/cli.py", line 139, in command
    await mqtt_client.send_command(cmd, json.loads(params) if params is not None else None)
  File "/usr/local/lib/python3.9/site-packages/roborock/cloud_api.py", line 168, in send_command
    self._diagnostic_data[method.name] = {"params": params, "response": response, "error": err}
AttributeError: 'str' object has no attribute 'name'

It was working, until I did an update on my system and recreated my docker container with latest `python-roborock` and `pyshark`

**Comment by Lash-L** [comment]
You should be using Python 3.10 not 3.9 that may be your issue. I'm not sure if 3.9 versions are provided via pypi

**Comment by Lash-L** [comment]
Gonna close this as I haven't heard from you since and i think the problem was just an incorrect python version
