### ISSUE TITLE
error executing command

### ISSUE THREAD

**Issue by Steph71** [humbertogontijo/python-roborock#231]
Hi, 

I am trying to interact with my robot using this library. However I am stuck with the most basic stuff.

I installed latest version (2.7.1) using pip. 

Login seems to succeed as roborock list-devices Returns a device ID an my Model.

However running the status command as indicated in the documentation, I am getting the error message below.

Anyone can help here ?

Best Regards
step

Edit: I am running python Python 3.12.5 on Windows 11

~~~bash
(roborock) PS C:\tmp\roborock> roborock -d command --device_id 21v6OihayZVOq4N6VGWzt1 --cmd status
DEBUG:roborock.cloud_api:[Q8 Max] Connecting to mqtt
DEBUG:roborock.cloud_api:[Q8 Max] Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=1mnoa4uPE7OoGXWvVW2T7k properties=None
INFO:roborock.cloud_api:[Q8 Max] Starting mqtt loop
DEBUG:roborock.cloud_api:[Q8 Max] Received CONNACK (0, Success) properties=[ReceiveMaximum : 16, TopicAliasMaximum : 0, MaximumQoS : 1, RetainAvailable : 0, MaximumPacketSize : 65536, WildcardSubscriptionAvailable : 1, SubscriptionIdentifierAvailable : 1, SharedSubscriptionAvailable : 1]
INFO:roborock.cloud_api:[Q8 Max] Connected to mqtt mqtt-eu-3.roborock.com:8883
DEBUG:roborock.cloud_api:[Q8 Max] Sending SUBSCRIBE (d0, m1) [(b'rr/m/o/10ZxJn9qjRIQ5EYox6YZfs/76eff133/21v6OihayZVOq4N6VGWzt1', {QoS=0, noLocal=False, retainAsPublished=False, retainHandling=0})]
INFO:roborock.cloud_api:[Q8 Max] Subscribed to topic rr/m/o/10ZxJn9qjRIQ5EYox6YZfs/76eff133/21v6OihayZVOq4N6VGWzt1
DEBUG:roborock.cloud_api:[Q8 Max] id=20001 Requesting method status with []
DEBUG:roborock.cloud_api:[Q8 Max] Sending PUBLISH (d0, q0, r0, m2), 'b'rr/m/i/10ZxJn9qjRIQ5EYox6YZfs/76eff133/21v6OihayZVOq4N6VGWzt1'', properties=None, ... (199 bytes)
DEBUG:roborock.cloud_api:[Q8 Max] Received SUBACK
DEBUG:roborock.cloud_api:[Q8 Max] Received PUBLISH (d0, q0, r0, m0), 'rr/m/o/10ZxJn9qjRIQ5EYox6YZfs/76eff133/21v6OihayZVOq4N6VGWzt1', properties=[], ...  (103 bytes)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\tmp\roborock\.venv\Scripts\roborock.exe\__main__.py", line 8, in <module>
  File "C:\tmp\roborock\.venv\Lib\site-packages\roborock\cli.py", line 200, in main
    return cli()
           ^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\roborock\util.py", line 69, in wrapped
    return loop.run_until_complete(func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\schoenfs\AppData\Roaming\uv\python\cpython-3.12.5-windows-x86_64-none\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\roborock\cli.py", line 139, in command
    await mqtt_client.send_command(cmd, json.loads(params) if params is not None else None)
  File "C:\tmp\roborock\.venv\Lib\site-packages\roborock\version_1_apis\roborock_client_v1.py", line 485, in send_command
    response = await self._send_command(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\roborock\version_1_apis\roborock_mqtt_client_v1.py", line 72, in _send_command
    return await self.send_message(roborock_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\roborock\version_1_apis\roborock_mqtt_client_v1.py", line 50, in send_message
    (response, err) = await async_response
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\roborock\.venv\Lib\site-packages\roborock\api.py", line 105, in _wait_response
    raise UnknownMethodError("Unknown method")
roborock.exceptions.UnknownMethodError: Unknown method
~~~

**Comment by Steph71** [comment]
This is related to networking restrictions in my corporate network. Therefore closing
