### ISSUE TITLE
Adding Qrevo Master fails

### ISSUE THREAD

**Issue by jwetzl** [humbertogontijo/python-roborock#261]
I already have a Roborock S7 and now added a Qrevo Master, however it is not being loaded in Home Assistant. Here are the relevant logs:

```
2024-12-22 16:38:42.949 WARNING (MainThread) [roborock.code_mappings] Missing RoborockFanSpeedQRevoMaster code: 106 - defaulting to 101
2024-12-22 16:38:42.949 WARNING (MainThread) [roborock.code_mappings] Missing RoborockMopIntensityQRevoMaster code: 204 - defaulting to 200
2024-12-22 16:38:42.950 WARNING (MainThread) [roborock.code_mappings] Missing RoborockDockTypeCode code: 14 - defaulting to 'unknown'
2024-12-22 16:40:00.152 ERROR (MainThread) [roborock.containers] <enum 'RoborockMopModeCode'> has no members; specify 'names=()' if you meant to create a new, empty, enum
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/roborock/containers.py", line 124, in convert_to_class_obj
    converted_value = class_type(value)
  File "/usr/local/lib/python3.13/enum.py", line 726, in __call__
    raise TypeError(
            f"{cls} has no members; specify 'names=()' if you meant to create a new, empty, enum"
            )
TypeError: <enum 'RoborockMopModeCode'> has no members; specify 'names=()' if you meant to create a new, empty, enum
2024-12-22 16:40:00.153 ERROR (MainThread) [homeassistant.components.roborock.coordinator] Unexpected error fetching roborock data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/roborock/coordinator.py", line 110, in _async_update_data
    await self._update_device_prop()
  File "/usr/src/homeassistant/homeassistant/components/roborock/coordinator.py", line 99, in _update_device_prop
    device_prop = await self.api.get_prop()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/roborock/version_1_apis/roborock_client_v1.py", line 271, in get_prop
    status, clean_summary, consumable = await asyncio.gather(
                                        ^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )  # type: Status, CleanSummary, Consumable # type: ignore
    ^
  File "/usr/local/lib/python3.13/site-packages/roborock/version_1_apis/roborock_client_v1.py", line 172, in get_status
    data = self._status_type.from_dict(await self.cache[CacheableAttribute.status].async_value())
  File "/usr/local/lib/python3.13/site-packages/roborock/containers.py", line 169, in from_dict
    return cls(**data)
  File "<string>", line 62, in __init__
  File "/usr/local/lib/python3.13/site-packages/roborock/containers.py", line 539, in __post_init__
    self.mop_mode_name = self.mop_mode.name
                         ^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'name'
2024-12-22 16:40:00.157 WARNING (MainThread) [homeassistant.components.roborock] Not setting up Qrevo because the coordinator failed to get data for the first time using the offline client Please create an issue with the following error included: 'int' object has no attribute 'name'
2024-12-22 16:40:05.095 ERROR (MainThread) [homeassistant.components.image] Platform roborock does not generate unique IDs. ID 3zwmalcs443v7mfhwjrl5b_map_ already exists - ignoring image.roborock_s7
2024-12-22 16:41:08.152 ERROR (MainThread) [roborock.api] [Qrevo] id=1 Timeout after 4 seconds
```

Any help would be appreciated!

**Comment by Lash-L** [comment]
This is fixed in the latest version of the library. It is fixed in home assistant as well in 2025.1
